FROM node:10-alpine AS base

WORKDIR /app

COPY . .

RUN apk add --no-cache make gcc g++ python python3 linux-headers udev git eudev-dev libusb-dev pkgconf
RUN git config --global url."https://github.com".insteadOf "ssh://git@github.com"
RUN npm config set strict-ssl false
RUN npm set progress=false && npm config set depth 0
RUN npm ci --unsafe-perm

# Build without minification (UglifyJS doesn't support ES6+)
RUN npx webpack --progress --colors

# Override the comm-server's bundled frontend with ALL freshly built files
RUN cp /app/dist/* /app/node_modules/lw.comm-server/app/

#
# ---- Release ----
FROM node:10-alpine

ENV ENV="production"
ENV NODE_ENV="production"

RUN apk add --no-cache udev eudev

WORKDIR /app
COPY --from=base /app ./

EXPOSE 8000

CMD [ "npm", "run", "start-server" ]
